//
//  ecs/core/core_systems.h
//  List of core ECS systems
//  Copyright (c) 2026 Carlos Camacho. All rights reserved.
//
#ifndef CORGO_ECS_CORE_SYSTEMS_H
#define CORGO_ECS_CORE_SYSTEMS_H

#include "system.h"

////////////////////////////////////////////////////////////////////////
// Test Systems Definitions
////////////////////////////////////////////////////////////////////////

// Test dependecy, just the debug component
#define CE_CORE_TEST_SYSTEM_DEPENDENCIES \
    REQUIRE_COMPONENT(CE_CORE_DEBUG_COMPONENT, debugComponent)

// Test dependency with relationship
#define CE_CORE_TEST_SYSTEM_DEPENDENCIES_REL \
    REQUIRE_COMPONENT(CE_CORE_DEBUG_COMPONENT, debugComponent)\
    REQUIRE_RELATIONSHIP(CE_RELATIONSHIP_PARENT, relatedComponent)

#define CE_CORE_TEST_SYSTEM_DEPENDENCIES_NO_STORAGE \
    REQUIRE_COMPONENT(CE_CORE_DEBUG_COMPONENT, debugComponent)\
    REQUIRE_COMPONENT(CE_CORE_NO_STORAGE_COMPONENT_TEST, noStorageComponent)

// The systems CE_CORE_TEST_SYSTEM_* are for testing purposes, only included on test builds
#ifdef CE_CORE_TEST_MODE
#define CE_SYSTEM_TEST_CORE(CE_SYSTEM_DESC) \
	CE_SYSTEM_DESC(CE_CORE_TEST_SYSTEM_DISPLAY, CE_ECS_SYSTEM_RUN_ORDER_AUTO, CE_ECS_SYSTEM_RUN_PHASE_DEFAULT, CE_ECS_SYSTEM_RUN_FREQUENCY_DISPLAY, CE_CORE_TEST_SYSTEM_DEPENDENCIES)\
    CE_SYSTEM_DESC(CE_CORE_TEST_SYSTEM_HALF_DISPLAY, CE_ECS_SYSTEM_RUN_ORDER_AUTO, CE_ECS_SYSTEM_RUN_PHASE_EARLY, CE_ECS_SYSTEM_RUN_FREQUENCY_HALF_DISPLAY, CE_CORE_TEST_SYSTEM_DEPENDENCIES)\
    CE_SYSTEM_DESC(CE_CORE_TEST_SYSTEM_SECOND, CE_ECS_SYSTEM_RUN_ORDER_AUTO, CE_ECS_SYSTEM_RUN_PHASE_LATE, CE_ECS_SYSTEM_RUN_FREQUENCY_ONCE_PER_SECOND, CE_CORE_TEST_SYSTEM_DEPENDENCIES)\
    CE_SYSTEM_DESC(CE_CORE_TEST_SYSTEM_REL, CE_ECS_SYSTEM_RUN_ORDER_AUTO, CE_ECS_SYSTEM_RUN_PHASE_DEFAULT, CE_ECS_SYSTEM_RUN_FREQUENCY_DISPLAY, CE_CORE_TEST_SYSTEM_DEPENDENCIES_REL)\
    CE_SYSTEM_DESC(CE_CORE_TEST_SYSTEM_SCENE_ORDER, CE_ECS_SYSTEM_RUN_ORDER_SCENETREE, CE_ECS_SYSTEM_RUN_PHASE_DEFAULT, CE_ECS_SYSTEM_RUN_FREQUENCY_DISPLAY, CE_CORE_TEST_SYSTEM_DEPENDENCIES)\
    CE_SYSTEM_DESC(CE_CORE_TEST_SYSTEM_NO_STORAGE, CE_ECS_SYSTEM_RUN_ORDER_AUTO, CE_ECS_SYSTEM_RUN_PHASE_DEFAULT, CE_ECS_SYSTEM_RUN_FREQUENCY_DISPLAY, CE_CORE_TEST_SYSTEM_DEPENDENCIES_NO_STORAGE)
#else 
#define CE_SYSTEM_TEST_CORE(CE_SYSTEM_DESC)
#endif // CE_CORE_TEST_MODE

////////////////////////////////////////////////////////////////////////
// Core Systems Definitions
////////////////////////////////////////////////////////////////////////

#define CE_CORE_DEBUG_SYSTEM_DEPENDENCIES \
    REQUIRE_COMPONENT(CE_CORE_DEBUG_COMPONENT, debugComponent)

#define CE_SYSTEM_DESC_CORE(CE_SYSTEM_DESC) \
    CE_SYSTEM_TEST_CORE(CE_SYSTEM_DESC)\
    CE_SYSTEM_DESC(CE_CORE_ENTITY_DEBUG_SYSTEM, CE_ECS_SYSTEM_RUN_ORDER_AUTO, CE_ECS_SYSTEM_RUN_PHASE_LATE, CE_ECS_SYSTEM_RUN_FREQUENCY_HALF_DISPLAY, CE_CORE_DEBUG_SYSTEM_DEPENDENCIES)


////////////////////////////////////////////////////////////////////////
// Core Global Systems Definitions
////////////////////////////////////////////////////////////////////////

#define CE_GLOBAL_SYSTEM_DESC_CORE(CE_GLOBAL_SYSTEM_DESC) \
    CE_GLOBAL_SYSTEM_DESC(CE_CORE_GLOBAL_DEBUG_SYSTEM, CE_ECS_SYSTEM_RUN_PHASE_LATE, CE_ECS_SYSTEM_RUN_FREQUENCY_ONCE_PER_SECOND)

#endif // CORGO_ECS_CORE_SYSTEMS_H