//
//  engine/systems.h
//  List of engine ECS systems
//  Copyright (c) 2025 Carlos Camacho. All rights reserved.
//

#ifndef CORGO_ENGINE_SYSTEMS_H
#define CORGO_ENGINE_SYSTEMS_H

#include "ecs/core/system.h"

// Debug systems
#ifdef CE_DEBUG_BUILD
#define CE_ENGINE_DEBUG_SYSTEM_DEPENDENCIES \
    REQUIRE_COMPONENT(CE_CORE_DEBUG_COMPONENT, debugComponent)

#define CE_ENGINE_DEBUG_SYSTEMS(CE_SYSTEM_DESC) \
    CE_SYSTEM_DESC(CE_ENGINE_ENTITY_DEBUG_SYSTEM, CE_ECS_SYSTEM_RUN_ORDER_AUTO, CE_ECS_SYSTEM_RUN_PHASE_DEBUG, CE_ECS_SYSTEM_RUN_FREQUENCY_DISPLAY, CE_ENGINE_DEBUG_SYSTEM_DEPENDENCIES)

#define CE_ENGINE_GLOBAL_DEBUG_SYSTEMS(CE_GLOBAL_SYSTEM_DESC) \
    CE_GLOBAL_SYSTEM_DESC(CE_ENGINE_GLOBAL_DEBUG_SYSTEM, CE_ECS_SYSTEM_RUN_PHASE_DEBUG, CE_ECS_SYSTEM_RUN_FREQUENCY_DISPLAY)

#else
#define CE_ENGINE_DEBUG_SYSTEMS(CE_SYSTEM_DESC)
#define CE_ENGINE_GLOBAL_DEBUG_SYSTEMS(CE_GLOBAL_SYSTEM_DESC)
#endif // CE_DEBUG_BUILD


#define CE_TEXT_LABEL_SYSTEM_DEPENDENCIES \
    REQUIRE_COMPONENT(CE_TEXT_LABEL_COMPONENT, textLabelComponent)\

#define CE_IMAGE_SYSTEM_DEPENDENCIES \
    REQUIRE_COMPONENT(CE_IMAGE_COMPONENT, imageComponent)\

#define CE_SYSTEM_DESC_ENGINE(CE_SYSTEM_DESC) \
    CE_SYSTEM_DESC(CE_TEXT_LABEL_RENDERER, CE_ECS_SYSTEM_RUN_ORDER_RENDER, CE_ECS_SYSTEM_RUN_PHASE_DEFAULT, CE_ECS_SYSTEM_RUN_FREQUENCY_DISPLAY, CE_TEXT_LABEL_SYSTEM_DEPENDENCIES)\
    CE_SYSTEM_DESC(CE_IMAGE_RENDERER, CE_ECS_SYSTEM_RUN_ORDER_RENDER, CE_ECS_SYSTEM_RUN_PHASE_DEFAULT, CE_ECS_SYSTEM_RUN_FREQUENCY_DISPLAY, CE_IMAGE_SYSTEM_DEPENDENCIES)\
    CE_ENGINE_DEBUG_SYSTEMS(CE_SYSTEM_DESC)
    

// Input reader system
#ifdef CE_BACKEND_PLAYDATE
#define CE_ENGINE_GLOBAL_INPUT_READER_SYSTEM CE_ENGINE_GLOBAL_INPUT_READER_PD_SYSTEM
#else
#define CE_ENGINE_GLOBAL_INPUT_READER_SYSTEM CE_ENGINE_GLOBAL_INPUT_READER_STUB_SYSTEM
#endif

#define CE_GLOBAL_SYSTEM_DESC_ENGINE(CE_GLOBAL_SYSTEM_DESC) \
    CE_GLOBAL_SYSTEM_DESC(CE_ENGINE_GLOBAL_INPUT_READER_SYSTEM, CE_ECS_SYSTEM_RUN_PHASE_DEFAULT, CE_ECS_SYSTEM_RUN_FREQUENCY_DISPLAY)\
    CE_GLOBAL_SYSTEM_DESC(CE_ENGINE_GLOBAL_INPUT_SYSTEM, CE_ECS_SYSTEM_RUN_PHASE_DEFAULT, CE_ECS_SYSTEM_RUN_FREQUENCY_DISPLAY)\
    CE_GLOBAL_SYSTEM_DESC(CE_ENGINE_GLOBAL_SCENE_SCRIPT_SYSTEM, CE_ECS_SYSTEM_RUN_PHASE_DEFAULT, CE_ECS_SYSTEM_RUN_FREQUENCY_DISPLAY)\
    CE_ENGINE_GLOBAL_DEBUG_SYSTEMS(CE_GLOBAL_SYSTEM_DESC)



#endif // CORGO_ENGINE_SYSTEMS_H

