//
//  engine/systems.h
//  List of engine ECS systems
//  Copyright (c) 2025 Carlos Camacho. All rights reserved.
//

#ifndef CORGO_ENGINE_SYSTEMS_H
#define CORGO_ENGINE_SYSTEMS_H

#include "ecs/core/system.h"

#define CE_TEXT_LABEL_SYSTEM_DEPENDENCIES \
    REQUIRE_COMPONENT(CE_TEXT_LABEL_COMPONENT, textLabelComponent)\

#define CE_SYSTEM_DESC_ENGINE(CE_SYSTEM_DESC) \
    CE_SYSTEM_DESC(CE_TEXT_LABEL_RENDERER, CE_ECS_SYSTEM_RUN_ORDER_RENDER, CE_ECS_SYSTEM_RUN_PHASE_DEFAULT, CE_ECS_SYSTEM_RUN_FREQUENCY_DISPLAY, CE_TEXT_LABEL_SYSTEM_DEPENDENCIES)\
    

// Input reader system
#ifdef CE_BACKEND_PLAYDATE
#define CE_ENGINE_GLOBAL_INPUT_READER_SYSTEM CE_ENGINE_GLOBAL_INPUT_READER_PD_SYSTEM
#else
#define CE_ENGINE_GLOBAL_INPUT_READER_SYSTEM CE_ENGINE_GLOBAL_INPUT_READER_STUB_SYSTEM
#endif

#define CE_GLOBAL_SYSTEM_DESC_ENGINE(CE_GLOBAL_SYSTEM_DESC) \
    CE_GLOBAL_SYSTEM_DESC(CE_ENGINE_GLOBAL_INPUT_READER_SYSTEM, CE_ECS_SYSTEM_RUN_PHASE_DEFAULT, CE_ECS_SYSTEM_RUN_FREQUENCY_DISPLAY)\
    CE_GLOBAL_SYSTEM_DESC(CE_ENGINE_GLOBAL_INPUT_SYSTEM, CE_ECS_SYSTEM_RUN_PHASE_DEFAULT, CE_ECS_SYSTEM_RUN_FREQUENCY_DISPLAY)\
    CE_GLOBAL_SYSTEM_DESC(CE_ENGINE_GLOBAL_SCENE_SCRIPT_SYSTEM, CE_ECS_SYSTEM_RUN_PHASE_DEFAULT, CE_ECS_SYSTEM_RUN_FREQUENCY_DISPLAY)\


#endif // CORGO_ENGINE_SYSTEMS_H

