//
//  engine/systems.h
//  List of engine ECS systems
//  Copyright (c) 2025 Carlos Camacho. All rights reserved.
//

#ifndef CORGO_ENGINE_SYSTEMS_H
#define CORGO_ENGINE_SYSTEMS_H

#include "ecs/core/system.h"

#define CE_TEXT_LABEL_SYSTEM_DEPENDENCIES \
    REQUIRE_COMPONENT(CE_TEXT_LABEL_COMPONENT, textLabelComponent)\
    REQUIRE_COMPONENT(CE_TRANSFORM_COMPONENT, transformComponent)

#define CE_SYSTEM_DESC_ENGINE(X) \
    X(CE_TEXT_LABEL_SYSTEM, CE_ECS_SYSTEM_RUN_ORDER_SCENETREE, CE_ECS_SYSTEM_RUN_PHASE_DEFAULT, CE_ECS_SYSTEM_RUN_FREQUENCY_DISPLAY, CE_TEXT_LABEL_SYSTEM_DEPENDENCIES)

#endif // CORGO_ENGINE_SYSTEMS_H

