//
//  main.c
//  Copyright (c) 2025 Carlos Camacho. All rights reserved.
//

#include <stdlib.h>

// Corgo Engine version and build info (automatically generated by CMake)
#include "build_info.h"

// Include Playdate API
#include "pd_api.h"

// Include memory management first to properly set up CC
#include "engine/core/memory.h"
#include "engine/core/display.h"

// Include main ECS header
#include "engine/corgo.h"

#ifdef CE_ENGINE_INCLUDE_SAMPLE_SCENES
#include "engine/scenes.h"
#endif

// Global ECS context
CE_ECS_Context *ecsContext;

// Tick helper
float lastTickTime = 0.0f;

static int update(void* userdata);

#ifdef _WINDLL
__declspec(dllexport)
#endif
int eventHandler(PlaydateAPI* pd, PDSystemEvent event, uint32_t arg)
{
	(void)arg; // arg is currently only used for event = kEventKeyPressed
	CE_Result result;
	
	if ( event == kEventInit )
	{
		// Initialize Engine
#ifdef CE_BACKEND_PLAYDATE
		pd->system->logToConsole("Received PD Backend Handler");
		CE_SetPlaydateAPI(pd);
		pd->system->logToConsole("Playdate API: %p", pd);
		pd->system->logToConsole("Playdate API cached: %p", CE_GetPlaydateAPI());
		pd->system->resetElapsedTime();
#endif
		
		CE_Debug("Welcome to Corgo Engine!");
		CE_Debug("Build Date: %s", CE_BUILD_DATETIME);
		
		CE_Debug("Creating ECS Context");
		CE_ERROR_CODE errorCode;														
		ecsContext = CE_realloc(NULL, sizeof(CE_ECS_Context));
		
		if (ecsContext == NULL) {
			CE_Error("Failed to allocate memory for ECS context");
			return -1;
		}

		CE_Debug("ECS Context allocated at %p with size %u bytes", ecsContext, sizeof(CE_ECS_Context));

		if (CE_ECS_Init(ecsContext, &errorCode) != CE_OK) {
			CE_Error("ECS Initialization failed with error code: %s", CE_GetErrorMessage(errorCode));
			return -1;
		}
#ifdef CE_BACKEND_PLAYDATE
		CE_Debug("Engine Initialized in %f seconds", (double) pd->system->getElapsedTime());
		pd->system->resetElapsedTime();
#endif

#ifdef CE_BACKEND_PLAYDATE
		CE_Debug("Scene Graph Initialized in %f seconds", (double) pd->system->getElapsedTime());
#endif

		// Setup Screen
		CE_Display_SetRefreshRate(ecsContext, 60);

		// Load Scene
#ifdef CE_ENGINE_SET_START_SCENE
		CE_Debug("Loading start scene: " CE_STRINGIFY(CE_ENGINE_SET_START_SCENE));
		result = CE_Scene_RequestLoad(ecsContext, CE_SCENE_LOAD_FUNCTION(CE_ENGINE_SET_START_SCENE), &errorCode);
#else
		CE_Debug("Loading default scene: " CE_STRINGIFY(CE_ENGINE_DEFAULT_SCENE));
		result = CE_Scene_RequestLoad(ecsContext, CE_SCENE_LOAD_FUNCTION(CE_ENGINE_DEFAULT_SCENE), &errorCode);
#endif
		if (result != CE_OK) {
			CE_Error("Failed to load start scene: %s", CE_GetErrorMessage(errorCode));
			return -1;
		}

		// Enable debug if in a debug build
#ifdef CE_DEBUG_BUILD
		CE_Debug("Enabling debug mode");

		CE_Engine_SetGlobalDebug(ecsContext, true);

#if CE_SHOW_FPS
		CE_Engine_ShowFPSCounter(ecsContext, true);
#endif // CE_SHOW_FPS

#endif // CE_DEBUG_BUILD

#ifdef CE_BACKEND_PLAYDATE
		// Initialize timer
		pd->system->resetElapsedTime();
		lastTickTime = 0.0f;

		// Set update callback
		pd->system->setUpdateCallback(update, pd);
#endif
	}

	if (event == kEventTerminate)
	{
		CE_Debug("Shutting down Engine");
		// Cleanup ECS
		CE_ERROR_CODE errorCode;
		if (CE_ECS_Cleanup(ecsContext, &errorCode) != CE_OK) {
			CE_Error("ECS Cleanup failed with error code: %s", CE_GetErrorMessage(errorCode));
			return -1;
		}
	}
	
	return 0;
}

static int update(void* userdata)
{
	float currentTime = 0.0f;
	float deltaTime = 0.0f;
	CE_ERROR_CODE errorCode;

#ifdef CE_BACKEND_PLAYDATE
	PlaydateAPI* pd = userdata;
	
	currentTime = pd->system->getElapsedTime();
	deltaTime = currentTime - lastTickTime;
	lastTickTime = currentTime;
#endif

	if (CE_ECS_Tick(ecsContext, deltaTime, &errorCode) != CE_OK) {
		CE_Error("ECS Tick failed with result code: %d", CE_GetErrorMessage(errorCode));
		return -1;
	}

#if CE_ENGINE_ENABLE_ADAPTIVE_RENDERING
	if (CE_Engine_SceneGraph_IsDirty(ecsContext))
#endif
	{
		// Clear screen before rendering
		CE_Display_Clear(ecsContext);

		// Regenerate caches if needed
		if (CE_Engine_SceneGraph_UpdateRenderList(ecsContext, &errorCode) != CE_OK) {
			CE_Error("Failed to update scene graph render list with error code: %s", CE_GetErrorMessage(errorCode));
			return CE_ERROR;
		}

		// Render
		if (CE_ECS_TickRenderSystems(ecsContext, deltaTime, &errorCode) != CE_OK) {
			CE_Error("ECS Tick Render Systems failed with result code: %d", CE_GetErrorMessage(errorCode));
			return -1;
		}
#if CE_ENGINE_ENABLE_ADAPTIVE_RENDERING
		CE_Engine_SceneGraph_ClearDirty(ecsContext);
#endif
	}

#ifdef CE_DEBUG_BUILD
	if (CE_ECS_TickDebugSystems(ecsContext, deltaTime, &errorCode) != CE_OK) {
		CE_Error("ECS Tick Debug Systems failed with result code: %d", CE_GetErrorMessage(errorCode));
		return -1;
	}
#endif

	return 1;
}

