//
//  main.c
//  Copyright (c) 2025 Carlos Camacho. All rights reserved.
//

#include <stdlib.h>

// Corgo Engine version and build info (automatically generated by CMake)
#include "build_info.h"

// Include Playdate API
#include "pd_api.h"

// Include memory management first to properly set up CC
#include "engine/core/memory.h"
#include "engine/core/display.h"

// Include main ECS header
#include "ecs/ecs.h"

// Global ECS context
CE_ECS_Context *ecsContext;

// Tick helper
float lastTickTime = 0.0f;

static int update(void* userdata);
const char* fontpath = "/System/Fonts/Asheville-Sans-14-Bold.pft";
const char* font2path = "/System/Fonts/Roobert-10-Bold.pft";
LCDFont* font = NULL;

// Demo variables, global to keep it simple
uint16_t x = 0;
uint16_t y = 0;
uint16_t x_speed = 1;
uint16_t y_speed = 1;
CE_Id transformComponentId = CE_INVALID_ID;
CE_TransformComponent* transformComponent = NULL;
CE_TransformComponent* transformComponent2 = NULL;
CE_Id textLabelComponentId = CE_INVALID_ID;
CE_TextLabelComponent* textLabelComponent = NULL;

#ifdef _WINDLL
__declspec(dllexport)
#endif
int eventHandler(PlaydateAPI* pd, PDSystemEvent event, uint32_t arg)
{
	(void)arg; // arg is currently only used for event = kEventKeyPressed
	CE_Result result;
	
	if ( event == kEventInit )
	{
		// Initialize Engine
#ifdef CE_BACKEND_PLAYDATE
		pd->system->logToConsole("Received PD Backend Handler");
		CE_SetPlaydateAPI(pd);
		pd->system->logToConsole("Playdate API: %p", pd);
		pd->system->logToConsole("Playdate API cached: %p", CE_GetPlaydateAPI());
		pd->system->resetElapsedTime();

		// Set screen properties
		pd->display->setScale(1);
#endif
		CE_Debug("Welcome to Corgo Engine!");
		CE_Debug("Date Built: %s", CE_BUILD_DATETIME);
		
		CE_Debug("Creating ECS Context");
		CE_ERROR_CODE errorCode;														
		ecsContext = CE_realloc(NULL, sizeof(CE_ECS_Context));
		CE_Debug("ECS Context allocated at %p with size %u bytes", ecsContext, sizeof(CE_ECS_Context));

		if (ecsContext == NULL) {
			CE_Error("Failed to allocate memory for ECS context");
			return -1;
		}

		if (CE_ECS_Init(ecsContext, &errorCode) != CE_OK) {
			CE_Error("ECS Initialization failed with error code: %s", CE_GetErrorMessage(errorCode));
			return -1;
		}
		
		CE_Debug("Engine Initialized in %f seconds", (double) pd->system->getElapsedTime());

		// Initialize scene graph
		result = CE_Engine_SceneGraph_Init(ecsContext, &errorCode);
		if (result != CE_OK) {
			CE_Error("Failed to initialize scene graph: %s", CE_GetErrorMessage(errorCode));
			return -1;
		}

		// Demo code to print a text label using ECS
		// TODO: move this once scene management is implemented
		{
			CE_Id entityId = CE_INVALID_ID;
			result = CE_ECS_CreateEntity(ecsContext, &entityId, &errorCode);
			if (result != CE_OK) {
				CE_Error("Failed to create demo entity: %s", CE_GetErrorMessage(errorCode));
				return -1;
			}

			result = CE_Entity_AddComponent(ecsContext, entityId, CE_TRANSFORM_COMPONENT, &transformComponentId, (void**)&transformComponent, &errorCode);
			if (result != CE_OK) {
				CE_Error("Failed to add TransformComponent to demo entity: %s", CE_GetErrorMessage(errorCode));
				return -1;
			}

			result = CE_Entity_AddComponent(ecsContext, entityId, CE_TEXT_LABEL_COMPONENT, &textLabelComponentId, (void**)&textLabelComponent, &errorCode);
			if (result != CE_OK) {
				CE_Error("Failed to add TextLabelComponent to demo entity: %s", CE_GetErrorMessage(errorCode));
				return -1;
			}

			// Set text and font
			result = CE_TextLabelComponent_setText(ecsContext, textLabelComponent, transformComponent, "Hello, Corgo Engine!");
			if (result != CE_OK) {
				CE_Error("Failed to set text for TextLabelComponent: %s", CE_GetErrorMessage(errorCode));
				return -1;
			}
			result = CE_TextLabelComponent_setFont(ecsContext, textLabelComponent, transformComponent, font2path);
			if (result != CE_OK) {
				CE_Error("Failed to set font for TextLabelComponent: %s", CE_GetErrorMessage(errorCode));
				return -1;
			}

			// Add to graph
			CE_SceneGraph_AddChild(ecsContext, CE_SceneGraph_GetSceneRootId(ecsContext), entityId, false, &errorCode);
			if (result != CE_OK) {
				CE_Error("Failed to add demo entity to scene graph: %s", CE_GetErrorMessage(errorCode));
				return -1;
			}

			CE_Debug("Text bounds: %d x %d", transformComponent->m_width, transformComponent->m_height);
			CE_TransformComponent_setPosition(ecsContext, transformComponent, (CE_GetDisplayWidth(ecsContext)-transformComponent->m_width)/2, (CE_GetDisplayHeight(ecsContext)-transformComponent->m_height)/2);

			// Create a second entity to test the scene graph Z ordering
			CE_Id entityId2 = CE_INVALID_ID;
			CE_Id transformComponentId2 = CE_INVALID_ID;
			CE_Id textLabelComponentId2 = CE_INVALID_ID;
			CE_TextLabelComponent* textLabelComponent2 = NULL;

			result = CE_ECS_CreateEntity(ecsContext, &entityId2, &errorCode);
			if (result != CE_OK) {
				CE_Error("Failed to create demo entity 2: %s", CE_GetErrorMessage(errorCode));
				return -1;
			}

			result = CE_Entity_AddComponent(ecsContext, entityId2, CE_TRANSFORM_COMPONENT, &transformComponentId2, (void**)&transformComponent2, &errorCode);
			if (result != CE_OK) {
				CE_Error("Failed to add TransformComponent to demo entity 2: %s", CE_GetErrorMessage(errorCode));
				return -1;
			}

			result = CE_Entity_AddComponent(ecsContext, entityId2, CE_TEXT_LABEL_COMPONENT, &textLabelComponentId2, (void**)&textLabelComponent2, &errorCode);
			if (result != CE_OK) {
				CE_Error("Failed to add TextLabelComponent to demo entity 2: %s", CE_GetErrorMessage(errorCode));
				return -1;
			}

			// Set text and font
			result = CE_TextLabelComponent_setText(ecsContext, textLabelComponent2, transformComponent2, "WOOF!!");
			if (result != CE_OK) {
				CE_Error("Failed to set text for TextLabelComponent: %s", CE_GetErrorMessage(errorCode));
				return -1;
			}

			result = CE_TextLabelComponent_setFont(ecsContext, textLabelComponent2, transformComponent2, fontpath);
			if (result != CE_OK) {
				CE_Error("Failed to set font for TextLabelComponent 2: %s", CE_GetErrorMessage(errorCode));
				return -1;
			}
			
			textLabelComponent2->m_inverted = false; // Draw in white

			// Add to graph
			CE_SceneGraph_AddChild(ecsContext, entityId, entityId2, false, &errorCode);
			if (result != CE_OK) {
				CE_Error("Failed to add demo entity 2 to scene graph: %s", CE_GetErrorMessage(errorCode));
				return -1;
			}

			CE_TransformComponent_setZIndex(ecsContext, transformComponent2, 1); // Set above the first text label
		}

		CE_Display_SetRefreshRate(ecsContext, 60);

#ifdef CE_BACKEND_PLAYDATE
		// Initialize timer
		pd->system->resetElapsedTime();
		lastTickTime = 0.0f;

		// Set update callback
		pd->system->setUpdateCallback(update, pd);
#endif
	}

	if (event == kEventTerminate)
	{
		CE_Debug("Shutting down Engine");
		// Cleanup ECS
		CE_ERROR_CODE errorCode;
		if (CE_ECS_Cleanup(ecsContext, &errorCode) != CE_OK) {
			CE_Error("ECS Cleanup failed with error code: %s", CE_GetErrorMessage(errorCode));
			return -1;
		}
	}
	
	return 0;
}

static int update(void* userdata)
{
	float currentTime = 0.0f;
	float deltaTime = 0.0f;
	CE_ERROR_CODE errorCode;

#ifdef CE_BACKEND_PLAYDATE
	PlaydateAPI* pd = userdata;
	
	currentTime = pd->system->getElapsedTime();
	deltaTime = currentTime - lastTickTime;
	lastTickTime = currentTime;
#endif

	// Simple animation for demo
	{
		x += x_speed;
		y += y_speed;
		if (x <= 0 || x + transformComponent->m_width >= CE_GetDisplayWidth(ecsContext)) {
			x_speed = -x_speed;
		}
		if (y <= 0 || y + transformComponent->m_height >= CE_GetDisplayHeight(ecsContext)) {
			y_speed = -y_speed;
		}

		// Update transform component position
		CE_TransformComponent_setPosition(ecsContext, transformComponent, x, y);

		// Also update the second component to test Z ordering
		CE_TransformComponent_setPosition(ecsContext, transformComponent2, (transformComponent2->m_x + 2) % transformComponent->m_width, 0);
	}

	if (CE_ECS_Tick(ecsContext, deltaTime, &errorCode) != CE_OK) {
		CE_Error("ECS Tick failed with result code: %d", CE_GetErrorMessage(errorCode));
		return -1;
	}

	// Clear screen before rendering
	CE_Display_Clear(ecsContext);

	// Regenerate caches if needed
    if (CE_Engine_SceneGraph_UpdateRenderList(ecsContext, &errorCode) != CE_OK) {
        CE_Error("Failed to update scene graph render list with error code: %s", CE_GetErrorMessage(errorCode));
        return CE_ERROR;
    }

	// Render
	if (CE_ECS_TickRenderSystems(ecsContext, deltaTime, &errorCode) != CE_OK) {
		CE_Error("ECS Tick Render Systems failed with result code: %d", CE_GetErrorMessage(errorCode));
		return -1;
	}


#ifdef CE_BACKEND_PLAYDATE
	pd->system->drawFPS(0,0);
#endif

	return 1;
}

